name: Builder
on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron:  '0 0 * * *' # Every day at midnight
  workflow_dispatch:
    branches: [ main ]

jobs:
  build-debug:
    name: Build debug
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: WITH_DEBUG=true ./build.sh
  build-release:
    name: Build release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: ./build.sh
